# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#fbf9f9

# Main text color
theme[main_fg]=#1b1c1c

# Title color for boxes
theme[title]=#1b1c1c

# Highlight color for keyboard shortcuts
theme[hi_fg]=#4d5e6a

# Background color of selected item in processes box
theme[selected_bg]=#efedee

# Foreground color of selected item in processes box
theme[selected_fg]=#4d5e6a

# Color of inactive/disabled text
theme[inactive_fg]=#73787b

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#6f5841

# Background color of the percentage meters
theme[meter_bg]=#73787b

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#6f5841

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#00588c
theme[mem_box]=#007a8e
theme[net_box]=#2751f9
theme[proc_box]=#005f8b

# Box divider line and small boxes line color
theme[div_line]=#c3c7cb

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#007a8e
theme[temp_mid]=#008f68
theme[temp_end]=#003ee0

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#007191
theme[cpu_mid]=#007ca2
theme[cpu_end]=#0078b1

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#00588c
theme[free_mid]=#0078b1
theme[free_end]=#005f8b

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#007ca2
theme[cached_mid]=#005f8b
theme[cached_end]=#0078b1

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#8a4dff
theme[available_mid]=#2751f9
theme[available_end]=#003ee0

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#007a8e
theme[used_mid]=#007191
theme[used_end]=#0083b1

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#8a4dff
theme[download_mid]=#2751f9
theme[download_end]=#003ee0

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#007a8e
theme[upload_mid]=#007191
theme[upload_end]=#0083b1

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#007ca2
theme[process_mid]=#0078b1
theme[process_end]=#00588c
