-- Generated by nwg-displays on 2026-10-08 at 12:05:13. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@165.0",
    position = "3840x878",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.0",
    position = "1920x1042",
    scale = 1,
    vrr = 0
})
